repositories:
  - name: kubernetes
    url: https://kubernetes.github.io/ingress-nginx
  - name: bitnami
    url: https://charts.bitnami.com/bitnami

releases:
  - name: nginx
    namespace: default
    chart: kubernetes/nginx-ingress
    version: 4.9.1
  - name: postgresql
    namespace: postgresql
    createNamespace: true
    chart: bitnami/postgresql-ha
    version: 13.2.3
