repositories:
  - name: codecentric
    url: https://codecentric.github.io/helm-charts
  - name: bitnami
    url: https://charts.bitnami.com/bitnami

releases:
  - name: postgresql
    namespace: postgresql
    createNamespace: true
    chart: bitnami/postgresql-ha
    version: 13.2.3
  - name: keycloak
    namespace: keycloak
    createNamespace: true
    chart: codecentric/keycloak
    version: 18.4.4
