repositories:
  - name: stable
    url: https://charts.helm.sh/stable
  - name: bitnami
    url: https://charts.bitnami.com/bitnami

releases:
  - name: nginx
    namespace: default
    chart: stable/nginx-ingress
    version: latest
    values:
      controller:
        service:
          type: LoadBalancer
  - name: postgresql
    namespace: postgresql
    createNamespace: true
    chart: bitnami/postgresql-ha
    version: 13.2.3
