repositories:
  - name: ingress-nginx
    url: https://kubernetes.github.io/ingress-nginx
  - name: bitnami
    url: https://charts.bitnami.com/bitnami

releases:
  - name: postgresql
    namespace: postgresql
    createNamespace: true
    chart: bitnami/postgresql-ha
    version: 13.2.3
